### ISSUE TITLE
Sign Up Issue

### ISSUE THREAD

**Issue by Poach-GitHub** [walcottkenneth/CSC480_Project#6]
**After submitting on /signup page error message displays.** 
<img width="1706" alt="Screenshot 2023-01-29 at 10 42 15 AM" src="https://user-images.githubusercontent.com/106898412/215354527-439c75b9-504f-4000-9b1c-41393c8dd406.png">

### Log
127.0.0.1 - - [29/Jan/2023 12:36:14] "POST /signup HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/admin/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/admin/Desktop/Code/CSC480_Project/Flask Web App/website/auth.py", line 65, in signup
    if request.form.getlist('employee')[0] == 'on':
IndexError: list index out of range
127.0.0.1 - - [29/Jan/2023 12:36:14] "GET /signup?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Jan/2023 12:36:14] "GET /signup?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Jan/2023 12:36:14] "GET /signup?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

**Comment by Poach-GitHub** [comment]
Created branch David-loginPatch

**Comment by Poach-GitHub** [comment]
#david-loginPatch fixes issue
 **auth.py - line 65**
from
+             if request.form.getlist('employee')[0] == 'on':
 into
+             if request.form.getlist('employee') == ['on']:
